
import { RateCategory } from '../types';
import type { TdsRate } from '../types';

export const TDS_RATES: TdsRate[] = [
  // Domestic Transactions
  { id: 'dom-192', category: RateCategory.DOMESTIC, section: '192', natureOfPayment: 'Salaries', threshold: '-', rate1Label: 'Indv / HUF', rate1Value: 'Slab Rate', rate2Label: 'Others', rate2Value: 'Slab Rate' },
  { id: 'dom-192a', category: RateCategory.DOMESTIC, section: '192A', natureOfPayment: 'Premature withdrawal from EPF', threshold: '50,000', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '-' },
  { id: 'dom-193', category: RateCategory.DOMESTIC, section: '193', natureOfPayment: 'Interest on Securities', threshold: '10,000', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194', category: RateCategory.DOMESTIC, section: '194', natureOfPayment: 'Dividends', threshold: '10,000', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194a-banks', category: RateCategory.DOMESTIC, section: '194A', natureOfPayment: 'Interest (Banks)', threshold: '50,000', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194a-sr-citizen', category: RateCategory.DOMESTIC, section: '194A', natureOfPayment: 'Interest - Senior Citizen (Banks)', threshold: '1 Lakh', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194a-others', category: RateCategory.DOMESTIC, section: '194A', natureOfPayment: 'Interest (Others)', threshold: '10,000', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194b', category: RateCategory.DOMESTIC, section: '194B', natureOfPayment: 'Winning from Lotteries', threshold: '10,000', rate1Label: 'Indv / HUF', rate1Value: '30%', rate2Label: 'Others', rate2Value: '30%' },
  { id: 'dom-194ba', category: RateCategory.DOMESTIC, section: '194BA', natureOfPayment: 'Winnings from online games', threshold: '-', rate1Label: 'Indv / HUF', rate1Value: '30%', rate2Label: 'Others', rate2Value: '30%' },
  { id: 'dom-194bb', category: RateCategory.DOMESTIC, section: '194BB', natureOfPayment: 'Winning from Horse Race', threshold: '10,000', rate1Label: 'Indv / HUF', rate1Value: '30%', rate2Label: 'Others', rate2Value: '30%' },
  { id: 'dom-194c-single', category: RateCategory.DOMESTIC, section: '194C', natureOfPayment: 'Contractor - Single Transaction', threshold: '30,000', rate1Label: 'Indv / HUF', rate1Value: '1%', rate2Label: 'Others', rate2Value: '2%' },
  { id: 'dom-194c-fy', category: RateCategory.DOMESTIC, section: '194C', natureOfPayment: 'Contractor - During the F.Y.', threshold: '1 Lakh', rate1Label: 'Indv / HUF', rate1Value: '1%', rate2Label: 'Others', rate2Value: '2%' },
  { id: 'dom-194c-transporter', category: RateCategory.DOMESTIC, section: '194C', natureOfPayment: 'Transporter (44AE) declaration with PAN', threshold: '-', rate1Label: 'Indv / HUF', rate1Value: '-', rate2Label: 'Others', rate2Value: '-' },
  { id: 'dom-194d', category: RateCategory.DOMESTIC, section: '194D', natureOfPayment: 'Insurance Commission (15G-15H allowed)', threshold: '20,000', rate1Label: 'Indv / HUF', rate1Value: '2%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194da', category: RateCategory.DOMESTIC, section: '194DA', natureOfPayment: 'Payment received - Life insurance Policy', threshold: '1 Lakh', rate1Label: 'Indv / HUF', rate1Value: '2%', rate2Label: 'Others', rate2Value: '2%' },
  { id: 'dom-194ee', category: RateCategory.DOMESTIC, section: '194EE', natureOfPayment: 'Payment received - National Savings Scheme (NSS)', threshold: '2,500', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194f', category: RateCategory.DOMESTIC, section: '194F', natureOfPayment: 'Repurchase Units by MFs', threshold: '-', rate1Label: 'Indv / HUF', rate1Value: '-', rate2Label: 'Others', rate2Value: '-' },
  { id: 'dom-194g', category: RateCategory.DOMESTIC, section: '194G', natureOfPayment: 'Commission - Lottery', threshold: '20,000', rate1Label: 'Indv / HUF', rate1Value: '2%', rate2Label: 'Others', rate2Value: '2%' },
  { id: 'dom-194h', category: RateCategory.DOMESTIC, section: '194H', natureOfPayment: 'Commission / Brokerage', threshold: '20,000', rate1Label: 'Indv / HUF', rate1Value: '2%', rate2Label: 'Others', rate2Value: '2%' },
  { id: 'dom-194ia', category: RateCategory.DOMESTIC, section: '194I(a)', natureOfPayment: 'Rent for Plant & Machinery', threshold: '50,000 per month', rate1Label: 'Indv / HUF', rate1Value: '2%', rate2Label: 'Others', rate2Value: '2%' },
  { id: 'dom-194ib', category: RateCategory.DOMESTIC, section: '194I(b)', natureOfPayment: 'Rent of Land Building & Furniture', threshold: '50,000 per month', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194iaa', category: RateCategory.DOMESTIC, section: '194IA', natureOfPayment: 'Transfer of immovable property other than agricultural land', threshold: '50 Lakh', rate1Label: 'Indv / HUF', rate1Value: '1%', rate2Label: 'Others', rate2Value: '1%' },
  { id: 'dom-194ibb', category: RateCategory.DOMESTIC, section: '194IB', natureOfPayment: 'Rent payment by individual / HUF not covered u/s 194I', threshold: '50,000 per month', rate1Label: 'Indv / HUF', rate1Value: '2%', rate2Label: 'Others', rate2Value: '2%' },
  { id: 'dom-194ic', category: RateCategory.DOMESTIC, section: '194IC', natureOfPayment: 'Payment under specified Joint Development Agreement', threshold: '-', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194ja', category: RateCategory.DOMESTIC, section: '194J(a)', natureOfPayment: 'Fees - Technical Services, Call Centre, Royalty etc.', threshold: '50,000', rate1Label: 'Indv / HUF', rate1Value: '2%', rate2Label: 'Others', rate2Value: '2%' },
  { id: 'dom-194jb', category: RateCategory.DOMESTIC, section: '194J(b)', natureOfPayment: 'Fees - All other Professional Services', threshold: '50,000', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194k', category: RateCategory.DOMESTIC, section: '194K', natureOfPayment: 'Payment of dividend by mutual Funds', threshold: '10,000', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194la', category: RateCategory.DOMESTIC, section: '194LA', natureOfPayment: 'Compensation on transfer of immovable property', threshold: '5 Lakh', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194lb', category: RateCategory.DOMESTIC, section: '194LB', natureOfPayment: 'Interest from infrastructure debt fund (non-resident)', threshold: '-', rate1Label: 'Indv / HUF', rate1Value: '5%', rate2Label: 'Others', rate2Value: '5%' },
  { id: 'dom-194lba', category: RateCategory.DOMESTIC, section: '194LBA', natureOfPayment: 'Income from units of a business trust', threshold: '-', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194lbb', category: RateCategory.DOMESTIC, section: '194LBB', natureOfPayment: 'Income in respect of investment of investment fund', threshold: '-', rate1Label: 'Residents', rate1Value: '10%', rate2Label: 'Non-residents', rate2Value: '30% (Indv/HUF), 40% (Others)' },
  { id: 'dom-194lbc', category: RateCategory.DOMESTIC, section: '194LBC', natureOfPayment: 'Income in respect of investment in securitization trust', threshold: '-', rate1Label: 'Indv/HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10% (residents), 40% (non-residents)' },
  { id: 'dom-194ld', category: RateCategory.DOMESTIC, section: '194LD', natureOfPayment: 'Interest on certain bonds and Govt. Securities', threshold: '-', rate1Label: 'Indv / HUF', rate1Value: '5%', rate2Label: 'Others', rate2Value: '5%' },
  { id: 'dom-194m', category: RateCategory.DOMESTIC, section: '194M', natureOfPayment: 'Payment for Contracts, Brokerage, Professional Fees (Indv/HUF)', threshold: '50 Lakh', rate1Label: 'Indv / HUF', rate1Value: '2%', rate2Label: 'Others', rate2Value: '2%' },
  { id: 'dom-194n', category: RateCategory.DOMESTIC, section: '194N', natureOfPayment: 'Cash withdrawal > 1 Cr. (or 3 Cr. for co-op)', threshold: '1 Crore / 3 Crores', rate1Label: 'All', rate1Value: '2%' },
  { id: 'dom-194n-nofile', category: RateCategory.DOMESTIC, section: '194N', natureOfPayment: 'Cash withdrawal > 20 Lakh (ITR not filed for 3 yrs)', threshold: '20 Lakh - 1 Crore', rate1Label: 'All', rate1Value: '2%' },
  { id: 'dom-194n-nofile-high', category: RateCategory.DOMESTIC, section: '194N', natureOfPayment: 'Cash withdrawal > 1 Cr. (ITR not filed for 3 yrs)', threshold: '> 1 Crore', rate1Label: 'All', rate1Value: '5%' },
  { id: 'dom-194o', category: RateCategory.DOMESTIC, section: '194O', natureOfPayment: 'TDS on e-commerce participants', threshold: '5 Lakh', rate1Label: 'Indv / HUF', rate1Value: '0.1%', rate2Label: 'Others', rate2Value: '0.1%' },
  { id: 'dom-194p', category: RateCategory.DOMESTIC, section: '194P', natureOfPayment: 'TDS for Specified Sr. Citizen (>75 yrs, ITR not reqd)', threshold: '-', rate1Label: 'Indv / HUF', rate1Value: 'Slab Rate', rate2Label: 'Others', rate2Value: 'NA' },
  { id: 'dom-194q', category: RateCategory.DOMESTIC, section: '194Q', natureOfPayment: 'TDS on Purchase of Goods > 50 Lakh', threshold: 'In Excess of Rs. 50 Lakh', rate1Label: 'Indv / HUF', rate1Value: '0.1%', rate2Label: 'Others', rate2Value: '0.1%' },
  { id: 'dom-194r', category: RateCategory.DOMESTIC, section: '194R', natureOfPayment: 'Benefits or perquisites of business or profession', threshold: '20,000', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  { id: 'dom-194s', category: RateCategory.DOMESTIC, section: '194S', natureOfPayment: 'Payment for transfer of virtual digital asset (VDA)', threshold: '10,000', rate1Label: 'Indv / HUF', rate1Value: '1%', rate2Label: 'Others', rate2Value: '1%' },
  { id: 'dom-194sp', category: RateCategory.DOMESTIC, section: '194SP', natureOfPayment: 'Payment for VDA (in kind)', threshold: '10,000', rate1Label: 'Indv / HUF', rate1Value: '1%', rate2Label: 'Others', rate2Value: '1%' },
  { id: 'dom-194t', category: RateCategory.DOMESTIC, section: '194T', natureOfPayment: 'Payments by Partnership Firms to Partners', threshold: '20,000', rate1Label: 'Indv / HUF', rate1Value: '10%', rate2Label: 'Others', rate2Value: '10%' },
  // Foreign Transactions
  { id: 'for-192a', category: RateCategory.FOREIGN, section: '192A', natureOfPayment: 'Payment against EPF Scheme', threshold: '30,000', rate1Label: 'Rate', rate1Value: '10%' },
  { id: 'for-194e', category: RateCategory.FOREIGN, section: '194E', natureOfPayment: 'Non-resident Sportsman or Sports Assn.', threshold: '-', rate1Label: 'Rate', rate1Value: '20%' },
  { id: 'for-194lb', category: RateCategory.FOREIGN, section: '194LB', natureOfPayment: 'Interest from infrastructure debt fund (non-resident)', threshold: '-', rate1Label: 'Rate', rate1Value: '5%' },
  { id: 'for-194lba-units', category: RateCategory.FOREIGN, section: '194LBA', natureOfPayment: 'Certain income from units of a business trust', threshold: '-', rate1Label: 'Rate', rate1Value: '5%' },
  { id: 'for-194lba-a', category: RateCategory.FOREIGN, section: '194LBA(a)', natureOfPayment: 'Income u/s 10(23FC)(a) from business trust units', threshold: '-', rate1Label: 'Rate', rate1Value: '5%' },
  { id: 'for-194lba-b', category: RateCategory.FOREIGN, section: '194LBA(b)', natureOfPayment: 'Income u/s 10(23FC)(b) from business trust units', threshold: '-', rate1Label: 'Rate', rate1Value: '10%' },
  { id: 'for-194lba-c', category: RateCategory.FOREIGN, section: '194LBA(c)', natureOfPayment: 'Income u/s 10(23FCA) from business trust units', threshold: '-', rate1Label: 'Rate', rate1Value: '30%' },
  { id: 'for-194lbb', category: RateCategory.FOREIGN, section: '194LBB', natureOfPayment: 'Income on units of Investment Fund', threshold: '-', rate1Label: 'Rate', rate1Value: '30% / 40%' },
  { id: 'for-194lbc', category: RateCategory.FOREIGN, section: '194LBC', natureOfPayment: 'Income from investment in securitization trust', threshold: '-', rate1Label: 'Rate', rate1Value: '30% / 40%' },
  { id: 'for-194lc', category: RateCategory.FOREIGN, section: '194LC', natureOfPayment: 'Interest from specified company (non-resident)', threshold: '-', rate1Label: 'Rate', rate1Value: '5%' },
  { id: 'for-194ld', category: RateCategory.FOREIGN, section: '194LD', natureOfPayment: 'Interest on certain bonds and govt. securities', threshold: '-', rate1Label: 'Rate', rate1Value: '5%' },
  { id: 'for-194n', category: RateCategory.FOREIGN, section: '194N', natureOfPayment: 'Payment of certain amounts in cash', threshold: '-', rate1Label: 'Rate', rate1Value: '2%' },
  { id: 'for-194nf', category: RateCategory.FOREIGN, section: '194NF', natureOfPayment: 'Payment of cash to non-filers', threshold: '-', rate1Label: 'Rate', rate1Value: '1%' },
  { id: 'for-195a', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Non-resident Indian investment income', threshold: '-', rate1Label: 'Rate', rate1Value: '20%' },
  { id: 'for-195b', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Long-term capital gains u/s 115E (NRI)', threshold: '-', rate1Label: 'Rate', rate1Value: '12.5%' },
  { id: 'for-195c', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Long-term capital gains u/s 112', threshold: '-', rate1Label: 'Rate', rate1Value: '12.5%' },
  { id: 'for-195d', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Long-term capital gains u/s 112A', threshold: '-', rate1Label: 'Rate', rate1Value: '12.5%' },
  { id: 'for-195e', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Short-term capital gains u/s 111A', threshold: '-', rate1Label: 'Rate', rate1Value: '20%' },
  { id: 'for-195f', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Other long-term capital gains', threshold: '-', rate1Label: 'Rate', rate1Value: '12.5%' },
  { id: 'for-195g', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Interest on foreign currency borrowings', threshold: '-', rate1Label: 'Rate', rate1Value: '20%' },
  { id: 'for-195h', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Royalty (copyright, book, software)', threshold: '-', rate1Label: 'Rate', rate1Value: '20%' },
  { id: 'for-195i', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Royalty (other)', threshold: '-', rate1Label: 'Rate', rate1Value: '20%' },
  { id: 'for-195j', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Fees for technical services', threshold: '-', rate1Label: 'Rate', rate1Value: '20%' },
  { id: 'for-195k', category: RateCategory.FOREIGN, section: '195', natureOfPayment: 'Any other income', threshold: '-', rate1Label: 'Rate', rate1Value: '30%' },
  { id: 'for-196a', category: RateCategory.FOREIGN, section: '196A', natureOfPayment: 'Foreign Company being unit holder in Mutual Fund', threshold: '-', rate1Label: 'Rate', rate1Value: '20%' },
  { id: 'for-196b', category: RateCategory.FOREIGN, section: '196B', natureOfPayment: 'Units held by Off-shore Fund', threshold: '-', rate1Label: 'Rate', rate1Value: '12.5%' },
  { id: 'for-196c', category: RateCategory.FOREIGN, section: '196C', natureOfPayment: 'Income from Foreign Currency Bonds', threshold: '-', rate1Label: 'Rate', rate1Value: '12.5%' },
  { id: 'for-196d', category: RateCategory.FOREIGN, section: '196D', natureOfPayment: 'Income of FII on Securities', threshold: '-', rate1Label: 'Rate', rate1Value: '20%' },
  { id: 'for-196da', category: RateCategory.FOREIGN, section: '196DA', natureOfPayment: 'Income of specified fund from securities', threshold: '-', rate1Label: 'Rate', rate1Value: '10%' },
  // TCS
  { id: 'tcs-a', category: RateCategory.TCS, code: 'A', natureOfPayment: 'Alcoholic Liquor for human consumption & Tendu leaves', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-b', category: RateCategory.TCS, code: 'B', natureOfPayment: 'Timber obtained under a forest lease or other mode', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '2%' },
  { id: 'tcs-c', category: RateCategory.TCS, code: 'C', natureOfPayment: 'Timber obtained under any other mode other than forest lease', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '2%' },
  { id: 'tcs-d', category: RateCategory.TCS, code: 'D', natureOfPayment: 'Any other forest produce not being a timber or Tendu leaves', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '2%' },
  { id: 'tcs-e', category: RateCategory.TCS, code: 'E', natureOfPayment: 'Scrap', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-f', category: RateCategory.TCS, code: 'F', natureOfPayment: 'Parking Lot', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '2%' },
  { id: 'tcs-g', category: RateCategory.TCS, code: 'G', natureOfPayment: 'Toll Plaza', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '2%' },
  { id: 'tcs-h', category: RateCategory.TCS, code: 'H', natureOfPayment: 'Mining & Quarrying', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '2%' },
  { id: 'tcs-i', category: RateCategory.TCS, code: 'I', natureOfPayment: 'Tendu Leaves', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '5%' },
  { id: 'tcs-j', category: RateCategory.TCS, code: 'J', natureOfPayment: 'Minerals', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-k', category: RateCategory.TCS, code: 'K', natureOfPayment: 'Bullion & Jewellery', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-l', category: RateCategory.TCS, code: 'L', natureOfPayment: 'Sale of Motor Vehicle (exceeding Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-m', category: RateCategory.TCS, code: 'M', natureOfPayment: 'TCS on sale in cash of any goods (FY 2016-17)', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-ma', category: RateCategory.TCS, code: 'MA', natureOfPayment: 'Sale of wrist watch (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-mb', category: RateCategory.TCS, code: 'MB', natureOfPayment: 'Sale of art piece (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-mc', category: RateCategory.TCS, code: 'MC', natureOfPayment: 'Sale of collectibles (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-md', category: RateCategory.TCS, code: 'MD', natureOfPayment: 'Sale of yacht, boat, helicopter etc. (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-me', category: RateCategory.TCS, code: 'ME', natureOfPayment: 'Sale of pair of sunglasses (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-mf', category: RateCategory.TCS, code: 'MF', natureOfPayment: 'Sale of bag such as handbag, purse (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-mg', category: RateCategory.TCS, code: 'MG', natureOfPayment: 'Sale of pair of shoes (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-mh', category: RateCategory.TCS, code: 'MH', natureOfPayment: 'Sale of sportswear and equipment (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-mi', category: RateCategory.TCS, code: 'MI', natureOfPayment: 'Sale of home theatre system (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-mj', category: RateCategory.TCS, code: 'MJ', natureOfPayment: 'Sale of horse for horse racing (> Rs. 10 Lakh)', threshold: '> 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-n', category: RateCategory.TCS, code: 'N', natureOfPayment: 'TCS on providing of any services (FY 2016-17)', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '1%' },
  { id: 'tcs-o', category: RateCategory.TCS, code: 'O', natureOfPayment: 'Overseas Tour Program Package', threshold: 'Up to 10 Lakh / Above 10 Lakh', rate1Label: 'TCS Rate', rate1Value: '5% / 20%' },
  { id: 'tcs-p', category: RateCategory.TCS, code: 'P', natureOfPayment: 'LRS - Educational Loan (Removed from 01/04/2025)', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '0%' },
  { id: 'tcs-q', category: RateCategory.TCS, code: 'Q', natureOfPayment: 'LRS-other purposes - Liberalized Remittance Scheme', threshold: '10 Lakh', rate1Label: 'TCS Rate', rate1Value: '20%' },
  { id: 'tcs-r', category: RateCategory.TCS, code: 'R', natureOfPayment: 'Sale of Goods (Removed from 01/04/2025)', threshold: '-', rate1Label: 'TCS Rate', rate1Value: '0%' },
  { id: 'tcs-t', category: RateCategory.TCS, code: 'T', natureOfPayment: 'LRS - Education or Medical Treatment (not Code P)', threshold: '10 Lakh', rate1Label: 'TCS Rate', rate1Value: '5%' },
];
